### ISSUE TITLE
Problem with hentai

### ISSUE THREAD

**Issue by dubhead1** [whitecream01/WhiteCream-V0.0.1#23]
Hi,

I'm having an issue with the hentai section in WC - when I click on it I get a whitecream error

I'm running an M8S+ android box with kodi isengard

I have copied the following from the log file

18:23:55 T:1844674407204844442880 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

-NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: < type 'exceptions.NameError'>

Error Contents: global name 'rootDir' is not defined

Traceback (most recent call last):

"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.uwc/default.py", line 227 in <module>

elif mode == 30:hentaicraving.HCList(url)

"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.uwc/hentaicraving.py", line 44, in HCList

addHCDir(name, videourl, 31, img, desc)

"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.uwc/hentaicraving.py", line 118, in AddHCDir

fanart = os.path.join(rootDir, 'fanart.jpg')

NameError: global name 'rootDir' is not defined

-->End of Python script error report<--

**********************

Any suggestions?

**Comment by whitecream01** [comment]
This was fixed in version 1.1.11
