### ISSUE TITLE
Please add this to the next update. it's easy peasy.

### ISSUE THREAD

**Issue by 100Max** [whitecream01/WhiteCream-V0.0.1#36]
Please add this to the next update. it's easy peasy. Thanks man. :-D 

(This adds a link to chaterbate.. to show the New People. Female.)

In the: chaterbate.py..... Add this line somewhere near the top. or your choice man.

`utils.addDir('[COLOR hotpink]New - Female[/COLOR]','https://chaturbate.com/new-cams/female/?page=1',221,'','')`

Ok.. may as well add it for the males too.. but not my thing tho...

`utils.addDir('[COLOR hotpink]New - Male[/COLOR]','https://chaturbate.com/new-cams/male/?page=1',221,'','')`
- Tested.. works just fine for me.. It's usually only 2 pages at best. for New People.
- I added the New - Females ...under females at the top. just saying...

*ALSO: When you get bored and have some time.. you can add the chaterbates sister site:
 CamGasm. \* AND There is nothing wrong with their m3u8 streams. Tested. with Vlc player.
 It's pretty much just like the chaterbate site.. Only some url changes.
 Only it's not that many people there.. It's up to you though man for that one. 
.. for that one is not a big deal really.. for it's not that many people on there. a 1 page site.
- Keep up the great work man... we all appreciate it. we gotcha. :--)

**Comment by whitecream01** [comment]
For the next update, i added all new cams.
You can also choose in the settings which cams you want to see, female, male, couple, trans (enable/disable).

I will have a look at CamGasm.
