### ISSUE TITLE
with premiumize Account openload links not working

### ISSUE THREAD

**Issue by humiboy** [whitecream01/WhiteCream-V0.0.1#43]
Hello,

I have a premiumize account and configured in the url resolver settings. When I will use openload links in Kodi from uwc addon i become the message to pair my ip adress.

But I have premiumize and supportet openload links. Why i become the message to pair my ip adress and the links not working?
Have you a idea to fix this?

**Comment by whitecream01** [comment]
https://github.com/tknorris/script.module.urlresolver/issues/233#issuecomment-263363549
